# Load Data (features)

In [1]:
import numpy as np
import os
import pickle

In [2]:
input_path = '/content/drive/MyDrive/Into the Unknown/dataset/raw_features'

label_slouch1 = []
label_slouch2 = []
label_unbalanced = []

X_arrays = []

lst = os.listdir(input_path)
for people in lst:
  sub_lst = os.listdir(input_path + '/' + people)
  for label in sub_lst:
    path = input_path + '/' + people +'/' + label
    array_lst = os.listdir(path)
    for array_ in array_lst:
      array = np.load(path + '/' + array_)
      X_arrays.append(array)
      if label in ['B', 'B_D']:
        label_slouch1.append(1)
      else:
        label_slouch1.append(0)
      
      if label in ['C', 'C_D']:
        label_slouch2.append(1)
      else:
        label_slouch2.append(0)
      
      if label in ['D', 'B_D', 'C_D']:
        label_unbalanced.append(1)
      else:
        label_unbalanced.append(0)
      



In [3]:
X_arrays = np.array(X_arrays)
label_slouch1 = np.array(label_slouch1)
label_slouch2 = np.array(label_slouch2)
label_unbalanced = np.array(label_unbalanced)

In [4]:
path = '/content/drive/MyDrive/Into the Unknown/dataset'
save_path = path + '/' + 'X_arrays.npy'
np.save(save_path, X_arrays)

save_path = path +'/' + 'label_slouch1.npy'
np.save(save_path, label_slouch1)

save_path = path +'/' + 'label_slouch2.npy'
np.save(save_path, label_slouch2)

save_path = path +'/' + 'label_unbalanced.npy'
np.save(save_path, label_unbalanced)


In [5]:
X_arrays.shape, label_slouch1.shape

((339, 128), (339,))

In [6]:
models_path = '/content/drive/MyDrive/Into the Unknown/models/'

# Model for Slouch1

In [7]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X_arrays, label_slouch1, test_size = 0.2, random_state = 2023)
x_train.shape, y_train.shape

((271, 128), (271,))

In [8]:
x_train

array([[ 0.46546605,  0.60848612, -1.67769909, ...,  0.10081142,
        -0.23650327, -0.00979042],
       [ 0.53041083,  0.65302491, -0.97750127, ...,  0.01396143,
        -0.19412047,  0.00985688],
       [ 0.44533843,  0.64864618, -0.44583797, ...,  0.06006593,
         0.32162608,  0.04200053],
       ...,
       [ 0.49021867,  0.58760899, -1.27609015, ...,  0.08818513,
        -0.0831666 ,  0.091712  ],
       [ 0.42755255,  0.64799219, -1.35306656, ..., -0.05510658,
        -0.36615905, -0.04757744],
       [ 0.51687628,  0.39274648, -0.83816773, ..., -0.01997352,
        -0.07616097,  0.03680915]])

In [9]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(solver='lbfgs', alpha=1e-5,
                   hidden_layer_sizes=(10, 2), random_state=1)

clf.fit(x_train, y_train)

cur_path = models_path + 'slouch1.pkl'
pickle.dump(clf, open(cur_path, 'wb'))

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


In [10]:
clf = pickle.load(open(cur_path, 'rb'))

In [11]:
y_pred = clf.predict(x_test)
y_pred

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1])

In [12]:
y_test

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1])

In [14]:
from sklearn.metrics import recall_score
recall_score(y_test, y_pred)

0.875

In [15]:
clf.score(x_test, y_test)

0.9411764705882353

# Model for Slouch2


In [16]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X_arrays, label_slouch2, test_size = 0.2, random_state = 2023)
x_train.shape, y_train.shape

((271, 128), (271,))

In [17]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(solver='lbfgs', alpha=1e-5,
                   hidden_layer_sizes=(10, 2), random_state=1)

clf.fit(x_train, y_train)

cur_path = models_path + 'slouch2.pkl'
pickle.dump(clf, open(cur_path, 'wb'))

clf = pickle.load(open(cur_path, 'rb'))

clf.predict(x_test)

array([1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0])

In [18]:
y_test

array([1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0])

In [19]:
clf.score(x_test, y_test)

0.9411764705882353

In [20]:
recall_score(y_test,clf.predict(x_test))

0.8846153846153846

# Model for Unbalanced shoulders

In [21]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X_arrays, label_unbalanced, test_size = 0.2, random_state = 2023)
x_train.shape, y_train.shape

((271, 128), (271,))

In [22]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(solver='lbfgs', alpha=1e-5,
                   hidden_layer_sizes=(5, 2), random_state=1)

clf.fit(x_train, y_train)

cur_path = models_path + 'unbalanced.pkl'
pickle.dump(clf, open(cur_path, 'wb'))

clf = pickle.load(open(cur_path, 'rb'))

clf.predict(x_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1])

In [23]:
y_test

array([0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 1])

In [24]:
clf.score(x_test, y_test)

0.6029411764705882

In [25]:
recall_score(y_test,clf.predict(x_test))

0.23333333333333334